#!/bin/bash

set -e

printf "Environment variables:\\n"
printf "SOURCE_BRANCH=\"${SOURCE_BRANCH}\"\\n"
printf "SOURCE_COMMIT=\"${SOURCE_COMMIT}\"\\n"
printf "COMMIT_MSG=\"${COMMIT_MSG}\"\\n"
printf "DOCKER_REPO=\"${DOCKER_REPO}\"\\n"
printf "DOCKERFILE_PATH=\"${DOCKERFILE_PATH}\"\\n"
printf "CACHE_TAG=\"${CACHE_TAG}\"\\n"
printf "IMAGE_NAME=\"${IMAGE_NAME}\"\\n"

if test "${SOURCE_BRANCH}" = "master"; then
    DOCKERFILE_BASE_IMAGE="$(sed -n "s/ARG BASE_IMAGE=\"\(.*\)\"/\1/p" Dockerfile | sed -e '1 s/:/-/; t')"
    DOCKERFILE_VERSION="$(sed -n "s/ARG VERSION=\"\(.*\)\"/\1/p" Dockerfile)"
    LONG_TAG="${DOCKERFILE_VERSION}-on-${DOCKERFILE_BASE_IMAGE}"
    printf "Pushing ${IMAGE_NAME} also as ${DOCKER_REPO}:${LONG_TAG}\\n"
    docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:${LONG_TAG}"
    docker push "${DOCKER_REPO}:${LONG_TAG}"
    SHORT_TAG="${DOCKERFILE_VERSION}"
    printf "Pushing ${IMAGE_NAME} also as ${DOCKER_REPO}:${SHORT_TAG}\\n"
    docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:${SHORT_TAG}"
    docker push "${DOCKER_REPO}:${SHORT_TAG}"
else
    printf "Nothing to do\\n"
fi
